spring: 
    profiles: 
        active: 
        - dev
---
spring: 
    profiles: dev
    application: 
        name: springcloud-config-3344-dev
---
spring: 
    profiles: test
    application: 
        name: springcloud-config-3344-test