spring: 
    profiles: 
        active:
        - dev
---
spring: 
    profiles: dev
    application: 
        name: microservicecloud-config-yatou-dev
---
spring: 
    profiles: test
    application: 
        name: microservicecloud-config-yatou-test
​